package main

import (
	"bufio"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sync"
	"time"
)

// MemoryStore — pure file I/O for one agent's persistent memory.
// Mirrors `nanobot/agent/memory.py::MemoryStore` (lines 1–400 — the file
// I/O portion only; the Consolidator / Dream tiers live further down and
// belong to s10 / App. A respectively).
//
// The "four-file split" is the seed of upstream's "memory as
// interpretation" mental model:
//
//   <root>/history.jsonl    — append-only log of every turn (the truth).
//                              Hot-path. One JSONL line per HistoryEntry.
//   <root>/MEMORY.md        — long-term facts the LLM keeps about the world.
//                              Atomically replaced. The LLM's interpretation.
//   <root>/SOUL.md          — the agent's persona / identity.
//                              Atomically replaced.
//   <root>/USER.md          — the user's preferences as the agent sees them.
//                              Atomically replaced.
//   <root>/.cursor          — last successfully appended history cursor.
//                              Atomically replaced. Read by s10's Consolidator
//                              to know how much history is "fresh".
//
// Why two write paths? `history.jsonl` is append-only because turn data must
// never be silently lost — it's the audit trail. The three Markdown files
// are the LLM's *interpretation* of that history; they CAN be revised
// (the Dream cycle in App. A is exactly that). Atomic replace is the right
// shape for "the new state fully replaces the old"; append-only is the right
// shape for "another fact added to the record".
//
// Atomicity: WriteMemory and WriteCursor write to a tmp file in the same
// directory and `os.Rename` it onto the target. POSIX guarantees rename is
// atomic *within a filesystem* — so a crash in the middle leaves either the
// old file intact or the new file intact, never a half-written file.
// (The Markdown files all live under <root>, so the tmp file is on the
// same filesystem by construction.)
//
// Concurrency: AppendHistory is safe for concurrent callers because it
// holds an internal sync.Mutex AND opens the file with O_APPEND. POSIX
// guarantees an O_APPEND write up to PIPE_BUF bytes is atomic relative to
// other O_APPEND writes — but our entries can exceed PIPE_BUF, so we add
// the mutex as belt-and-braces. The other methods are not designed for
// concurrent writers (one MemoryStore = one agent's curated memory) but
// the read paths are safe to interleave with appends.

// HistoryEntry is one record in `history.jsonl`. The schema is intentionally
// small and stable — adding new fields is fine, removing them isn't (older
// jsonl files would no longer round-trip).
type HistoryEntry struct {
	TS        time.Time `json:"ts"`
	Role      string    `json:"role"`
	Content   string    `json:"content"`
	ToolsUsed []string  `json:"tools_used,omitempty"`
	Usage     Usage     `json:"usage,omitempty"`
}

// MemoryStore is the file-I/O layer.
type MemoryStore struct {
	root string

	// appendMu serializes AppendHistory across goroutines so a long write
	// can't be interleaved with another goroutine's append. POSIX O_APPEND
	// is atomic up to PIPE_BUF (typically 4096 bytes) but our JSON lines
	// can exceed that — the mutex covers the gap. Tests in
	// memory_test.go exercise this with 10 concurrent goroutines.
	appendMu sync.Mutex
}

// BootstrapFiles enumerates the curated Markdown files that s08's
// ContextBuilder will read into the system prompt. Naming matches upstream
// `nanobot/agent/context.py::BOOTSTRAP_FILES`.
//
// Note: AGENTS.md and TOOLS.md are read but not written by this store.
// They're typically authored by the user (AGENTS) or generated by the
// runtime tool registry (TOOLS). MEMORY/SOUL/USER are the three files the
// Dream cycle (App. A) revises.
var BootstrapFiles = []string{"AGENTS.md", "SOUL.md", "USER.md", "TOOLS.md"}

// NewMemoryStore prepares the on-disk layout. Mkdirs the root directory
// (parents included). Existing files are left intact.
func NewMemoryStore(root string) (*MemoryStore, error) {
	if root == "" {
		return nil, errors.New("MemoryStore: root must be non-empty")
	}
	if err := os.MkdirAll(root, 0o755); err != nil {
		return nil, fmt.Errorf("MemoryStore: mkdir %s: %w", root, err)
	}
	return &MemoryStore{root: root}, nil
}

// Root returns the on-disk root for inspection and testing.
func (m *MemoryStore) Root() string { return m.root }

// AppendHistory appends one HistoryEntry as a JSONL line and returns the
// new cursor (1-indexed line number of the appended entry).
//
// The cursor written to `<root>/.cursor` is the line count of `history.jsonl`
// after the append succeeded. Callers that have crashed mid-append will see
// a `.cursor` value lower than the actual line count on the next start —
// that's acceptable, since the cursor's role is "I successfully recorded
// up through line N", not "the file has exactly N lines".
func (m *MemoryStore) AppendHistory(entry HistoryEntry) (int, error) {
	m.appendMu.Lock()
	defer m.appendMu.Unlock()

	if entry.TS.IsZero() {
		entry.TS = time.Now().UTC()
	}

	historyPath := filepath.Join(m.root, "history.jsonl")
	f, err := os.OpenFile(historyPath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return 0, fmt.Errorf("MemoryStore.AppendHistory open: %w", err)
	}

	enc, err := json.Marshal(entry)
	if err != nil {
		_ = f.Close()
		return 0, fmt.Errorf("MemoryStore.AppendHistory encode: %w", err)
	}
	enc = append(enc, '\n')
	if _, err := f.Write(enc); err != nil {
		_ = f.Close()
		return 0, fmt.Errorf("MemoryStore.AppendHistory write: %w", err)
	}
	if err := f.Close(); err != nil {
		return 0, fmt.Errorf("MemoryStore.AppendHistory close: %w", err)
	}

	cursor, err := m.countLines(historyPath)
	if err != nil {
		return 0, fmt.Errorf("MemoryStore.AppendHistory count: %w", err)
	}
	if err := m.writeCursorAtomic(cursor); err != nil {
		return 0, fmt.Errorf("MemoryStore.AppendHistory cursor: %w", err)
	}
	return cursor, nil
}

// ReadCursor returns the last persisted cursor, or 0 if `.cursor` doesn't
// exist (a fresh agent). A malformed `.cursor` file is treated like
// "missing" — we return 0 rather than erroring, because the cursor is an
// optimization, not a correctness invariant: the worst case is we re-read
// the entire history.jsonl and re-detect the line count.
func (m *MemoryStore) ReadCursor() (int, error) {
	cursorPath := filepath.Join(m.root, ".cursor")
	b, err := os.ReadFile(cursorPath)
	if err != nil {
		if os.IsNotExist(err) {
			return 0, nil
		}
		return 0, fmt.Errorf("MemoryStore.ReadCursor: %w", err)
	}
	var c int
	if _, err := fmt.Sscanf(string(b), "%d", &c); err != nil {
		// Malformed cursor → treat as missing.
		return 0, nil
	}
	return c, nil
}

// WriteCursor persists `c` atomically. Same semantics as WriteMemory.
func (m *MemoryStore) WriteCursor(c int) error {
	return m.writeCursorAtomic(c)
}

// ReadMemory reads `<root>/<filename>` and returns its contents.
// A missing file is NOT an error — it returns "" so the ContextBuilder
// (s08) can call ReadMemory("MEMORY.md") on a fresh agent without error
// handling. Other I/O errors (permissions, etc.) DO surface.
func (m *MemoryStore) ReadMemory(filename string) (string, error) {
	path := filepath.Join(m.root, filename)
	b, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", fmt.Errorf("MemoryStore.ReadMemory %s: %w", filename, err)
	}
	return string(b), nil
}

// WriteMemory atomically writes `body` to `<root>/<filename>`.
// Implementation: write to a tmp file in the same directory, then
// `os.Rename`. POSIX guarantees rename within a filesystem is atomic, so a
// crash mid-write leaves either the old contents intact or the new
// contents intact — never a half-written file.
func (m *MemoryStore) WriteMemory(filename, body string) error {
	if filename == "" {
		return errors.New("MemoryStore.WriteMemory: filename must be non-empty")
	}
	target := filepath.Join(m.root, filename)
	return atomicWrite(target, []byte(body))
}

// ---------------------------------------------------------------------
// internals
// ---------------------------------------------------------------------

// writeCursorAtomic is shared between AppendHistory and WriteCursor.
func (m *MemoryStore) writeCursorAtomic(c int) error {
	target := filepath.Join(m.root, ".cursor")
	return atomicWrite(target, []byte(fmt.Sprintf("%d\n", c)))
}

// atomicWrite writes payload to target via a same-directory temp file and
// os.Rename. The temp file is deleted on error; on success it's the only
// artifact left behind (replacing target).
func atomicWrite(target string, payload []byte) error {
	dir := filepath.Dir(target)
	tmp, err := os.CreateTemp(dir, filepath.Base(target)+".tmp-*")
	if err != nil {
		return fmt.Errorf("atomicWrite tmpfile: %w", err)
	}
	tmpName := tmp.Name()
	cleanup := func() { _ = os.Remove(tmpName) }

	if _, err := tmp.Write(payload); err != nil {
		_ = tmp.Close()
		cleanup()
		return fmt.Errorf("atomicWrite write: %w", err)
	}
	if err := tmp.Sync(); err != nil {
		// fsync failure is unusual but tolerable on most ephemeral FSs;
		// don't make it fatal in tests / CI environments.
		_ = err
	}
	if err := tmp.Close(); err != nil {
		cleanup()
		return fmt.Errorf("atomicWrite close: %w", err)
	}
	if err := os.Rename(tmpName, target); err != nil {
		cleanup()
		return fmt.Errorf("atomicWrite rename: %w", err)
	}
	return nil
}

// countLines returns the number of '\n'-terminated lines in path.
// A file ending without a trailing newline still counts the last line.
// Empty file → 0. Missing file → 0 with no error (callers can treat that
// as "fresh agent").
func (m *MemoryStore) countLines(path string) (int, error) {
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return 0, nil
		}
		return 0, err
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	// Allow long JSON lines — default 64KB token cap is too small for
	// large tool-result content blocks.
	scanner.Buffer(make([]byte, 64*1024), 4*1024*1024)
	count := 0
	for scanner.Scan() {
		count++
	}
	if err := scanner.Err(); err != nil {
		return 0, err
	}
	return count, nil
}
